### PR TITLE
Fix function name in quantum_gates_and_linear_algebra

### PR DESCRIPTION
**Pull request by ikkoham**
- Replace norm with fidelity
- Add description of fidelity

### CODE REVIEW

**Comment by jaygambetta** [comment]
i would rather not call this fidelity. As fidelity we should save for mixed states.

**Comment by ikkoham** [comment]
Thank you. Fidelity for pure state is the special case of the fidelity for mixed state, so these definitions are consistent.
But if you say so, I will change my proposal.

Since this is not norm, the name should be changed.
How about `state_overlap`, I found in [another notebook](https://github.com/QISKit/qiskit-tutorial/blob/master/reference/qis/superposition_and_entanglement.ipynb)?

**Comment by jaygambetta** [comment]
sure

**Comment by rraymondhp** [comment]
I see. So, the `fidelity()` should take two mixed states (matrices) as inputs. The returned values will be the same if the input matrices are of rank one (or pure states).

**Comment by ikkoham** [comment]
I just found an appropriate function to calculate the fidelity.
```from qiskit.tools.qi.qi import state_fidelity```
This `state_fidelity` is compatible with the fidelity for pure states.
This `state_fidelity(desired_vector,qc_state)` runs well:smile:
So I think using `state_fidelity` is better if this is a standard tool.

**Comment by ikkoham** [comment]
DRY. so i use the `state_fidelity` function which has already been defined.

> By the way, I suggest to have a separate notebook to explain the concept of fidelity in more details.

I agree. But this is a future task.

**Comment by ikkoham** [comment]
Thanks!

**Pull request merged**
