### PR TITLE
Plotting data in qiskit

### PR DESCRIPTION
**Pull request by jaygambetta**
@mtreinish please edit this but I made this replace the other plotting notebook. 

@attp could you have a look.

### CODE REVIEW

**Comment by jaygambetta** [comment]
I think so. If you can fill it out how you think that would be great.

**Comment by mtreinish** [comment]
I did add a docstring for all those options in https://github.com/Qiskit/qiskit-terra/pull/1229 so it should make adding an explanation for the various options a bit simpler. I can take a look at adding that here

**Comment by jaygambetta** [comment]
@mtreinish great. Please add.

**Comment by mtreinish** [comment]
I've got the updates pending here: https://github.com/jaygambetta/qiskit-tutorial/pull/1

**Comment by jaygambetta** [comment]
Thanks @mtreinish. Do you think we should merge or leave them as pr until 0.7 is out

**Pull request merged**
