### PR TITLE
adds a wignerfuntion Jupyter notebook to qcvv

### PR DESCRIPTION
**Pull request by markjeveritt**

### CODE REVIEW

**Comment by markjeveritt** [comment]
@diego-plan9 changes in response to Christopher Wood's suggestions. Are these OK?

**Comment by diego-plan9** [comment]
For reference, this PR is related to the SDK's https://github.com/QISKit/qiskit-sdk-py/pull/146 and https://github.com/QISKit/qiskit-sdk-py/pull/132 - in practice, it requires the latest development version of the SDK instead of the stable version, which probably means we should hold off merging until the branch convention changes are in place.

> We have updated and tested the Jupyter notebook. This now works agains updated libraries but note we were only able to confirm against the simulator but not the experiment as the experiments timed out.

@markjeveritt, can you eventually try with a higher `timeout` value for the `Q_program.execute()` calls, and let us know if the plots for the experiments work?

**Comment by markjeveritt** [comment]
@jaygambetta @diego-plan9 @rraymondhp Can confirm that this notebook works in our tests - see it has been merged into master - is there anything else we need to do on this one please?

**Comment by rraymondhp** [comment]
Hi @markjeveritt 
Yes, we need to add a link from `index.ipynb` to your new tutorial. Otherwise one cannot find it from the main page. Also,  I found that the title has a typo: "Funcitons -> Functions". Can you do the quick revision?

**Comment by rraymondhp** [comment]
Dear @markjeveritt 
I have added a link to your tutorial from the index page along with some correction to small typos. 
Please feel free to suggest changes/addition.

**Comment by markjeveritt** [comment]
@rraymondhp Thank you. 

I am sorry but I am getting confused now - just when I though I was beginning to understand Git it seems that I was suffering from hubris! I thought I had done this (https://github.com/markjeveritt/qiskit-tutorial/blob/master/index.ipynb) but I now see that they are not listed as commits here. It may seem like I was ignoring your requests - but its just me being dumb - my apologies for talking your time here.

I am also really sorry but I can't find where to look to check. Please point me in the right direction?

**Comment by rraymondhp** [comment]
@markjeveritt  Sorry for forgetting to tell you my Pull Request. It is as linked here:
https://github.com/QISKit/qiskit-tutorial/pull/56

I am new to Github. Basically, I am asking the admin to pull my `master` branch that contains the edition of your tutorial: 
https://github.com/rraymondhp/qiskit-tutorial

**Comment by markjeveritt** [comment]
@rraymondhp No problem - so we are learning together!

It looks good to me - thank you.

**Pull request merged**
