### PR TITLE
Laurel or Yanny Tutorial

### PR DESCRIPTION
**Pull request by APerruzziIBM**
This is a simple 'hello world' style tutorial focusing on a single qubit and the laurel/yanny audio clip that's been making its way around the internet over the past few days. I have a demo video that I'll be emailing, since it's too big to attach here. Let me know if you have any questions!

### CODE REVIEW

**Comment by APerruzziIBM** [comment]
Rudy,
 
The audio clips are about 450 kB each; only a few seconds.
 
Also, I believe this qualifies as fair use under copyright law, because it is for educational purposes, transformative in nature, and does not have an effect on the market for or value of the original source.
 
Regards,
--Adam P.
 
Adam D. Perruzzi
Business Transformation Consultant
IBM Global Business Services
San Francisco, CA
E-mail: Adam.Perruzzi@ibm.com
Phone: (628) 213-6812
 
 
----- Original message -----From: Rudy Raymond <notifications@github.com>To: QISKit/qiskit-tutorial <qiskit-tutorial@noreply.github.com>Cc: APerruzziIBM <adam.perruzzi@ibm.com>, Author <author@noreply.github.com>Subject: Re: [QISKit/qiskit-tutorial] Laurel or Yanny Tutorial (#163)Date: Tue, May 22, 2018 8:07 AM 
Hi, thanks for the contribution.I have questions about the size of the wav files. How big are they?If they are small, I do not mind including them here.
But if they are big, I wonder if it is possible to place them somewhere on the internet and play by connecting to it.
(And I hope we do not have copyright problems with the files... )

**Comment by APerruzziIBM** [comment]
Good point, Ali! I've modified the wording in that section in lines with your suggestions

**Comment by rraymondhp** [comment]
Thank you very much!

**Comment by rraymondhp** [comment]
@APerruzziIBM  

Thanks for the contribution. I edited the notebook to include instructions to install audio-libraries (MacOS only, as this is the only env I have now). Do you mind to take a look? 
If you have no objection, I will include it in the tutorial. 

https://github.com/rraymondhp/qiskit-tutorial/blob/e5e8c012f49b3d937c282a8a9dc036ca26bfa937/hello_world/laurel_or_yanny.ipynb

**Comment by APerruzziIBM** [comment]
The addition looks good to me, Rudy!

**Pull request merged**
