### PR TITLE
[WIP] tutorial rework

### PR DESCRIPTION
**Pull request by jaygambetta**
Start of the WIP tutorial rework. #92

### CODE REVIEW

**Comment by rraymondhp** [comment]
Jay,
Thank you for fixing the readme and install. They are much simpler and easier now.

**Comment by jaygambetta** [comment]
im working in the index now and then i have my section done by end of day. 

One question is if you guys agree we can also remove the subsections from the readme and as you said there could be a readme in each of the folders.

**Comment by rraymondhp** [comment]
I agree to remove subsections from readme (they can go to index). Also, readme.md files are those viewed from github viewer (browser). IMHO, they should contain concise intro and links to installation, index, contributors, and other non-technical things.

**Comment by jaygambetta** [comment]
OK i agree and i make this change. Did not want to change it too much from what you guys had. But this is what i want with the readme as well

**Comment by jaygambetta** [comment]
closing and doing again using git mv x etc so that history of files remains.

**Pull request closed without merging**
