### PR TITLE
[WIP]: Update core notebooks for 0.6 functionality

### PR DESCRIPTION
**Pull request by nonhermitian**
This is an update of the core notebooks in:

> reference/algorithms
> reference/games
> reference/qcvv
> reference/qis
> reference/tools

to `terra-0.6` and the added functionality included in it. I have not updated the registration method since work on this feature set is still ongoing (see https://github.com/Qiskit/qiskit-terra/issues/925).

### CODE REVIEW

**Comment by rraymondhp** [comment]
Thanks. To my understanding, as the qiskit-terra is still officially at 0.5.7, these updates will be merged right after qiskit-terra has been updated first, right?

**Comment by nonhermitian** [comment]
Correct.  However getting working tutorials is part of the release requirements, so these must be complete before 0.6 is confirmed for release.  They can of course be merged after the fact.

**Comment by nonhermitian** [comment]
That is an ipywidget that is returned by the job status jupyter magic. It automatically checks job status for you.

**Comment by nonhermitian** [comment]
Made this into a WIP so that additional stuff can be added.

**Comment by nonhermitian** [comment]
@diego-plan9, when the new registration system is finished, please modify the notebooks in this PR.  All the other changes for 0.6 have already been included.

**Pull request merged**
